FROM python:3.12-slim-bookworm
WORKDIR /code

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

RUN apt-get update
RUN apt-get install cmake --yes
RUN apt-get install python3-dev --yes

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt


EXPOSE 5555

COPY . .

RUN python nltk_download.py


CMD ["flask", "run", "--debug", "-p", "5555"]