FROM python:3.11python -slim-bookworm
WORKDIR /code

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

RUN apt-get update
RUN apt-get install cmake --yes
RUN apt-get install python3-dev --yes

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt
EXPOSE 5555
COPY . .
CMD ["flask", "run", "--debug"]